# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       init-debug

# >> macros
# << macros

Summary:    A tiny init that starts a telnetd on a usb0 then starts init
Version:    0.1
Release:    1
Group:      System
License:    GPLv2
Source0:    %{name}-%{version}.tar.bz2
Source100:  init-debug.yaml
Requires:   busybox

%description
%{summary}.

%prep
%setup -q -n src

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
mkdir -p %{buildroot}
cp init-debug %{buildroot}
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%attr(755,root,root) /init-debug
# >> files
# << files
