#!/bin/sh
export PATH=/bin:/sbin:/usr/bin:/usr/sbin
echo "hello from /init"
write() {
        echo -n "$2" > $1
}
mount -t tmpfs tmpfs /boot
mount -t sysfs sysfs /sys
    write /sys/class/android_usb/android0/enable 0
    write /sys/class/android_usb/android0/idVendor 18D1
    write /sys/class/android_usb/android0/idProduct D001
    write /sys/class/android_usb/android0/functions rndis
    write /sys/class/android_usb/android0/iManufacturer Mer
    write /sys/class/android_usb/android0/iProduct Debugger
    write /sys/class/android_usb/android0/iSerial 123456789
    write /sys/class/android_usb/android0/enable 1
ifconfig usb0 10.42.0.5
/bin/umount -n /sys

/sbin/busybox telnetd -l/bin/sh &

sleep 5
exec /sbin/init --log-level=debug --log-target=kmsg &> /boot/systemd_stdouterr

    write /sys/class/android_usb/android0/enable 0
    write /sys/class/android_usb/android0/idVendor 18D1
    write /sys/class/android_usb/android0/idProduct D001
    write /sys/class/android_usb/android0/functions rndis
    write /sys/class/android_usb/android0/iManufacturer Mer
    write /sys/class/android_usb/android0/iProduct failed_to_start_init
    write /sys/class/android_usb/android0/iSerial 66666666
    write /sys/class/android_usb/android0/enable 1

sleep 86400
